# Generated by Django 5.0.1 on 2025-11-13 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('consistency', 'Consistency'), ('streak', 'Streak'), ('variety', 'Variety'), ('intensity', 'Intensity'), ('duration', 'Duration')], max_length=20)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20)),
                ('icon', models.CharField(help_text='Icon name or emoji', max_length=50)),
                ('color', models.CharField(help_text='Color for the badge', max_length=20)),
                ('requirement_type', models.CharField(choices=[('total_workouts', 'Total Workouts'), ('current_streak', 'Current Streak'), ('total_duration', 'Total Duration'), ('intense_workouts', 'Intense Workouts')], max_length=30)),
                ('requirement_value', models.IntegerField(help_text='Value needed to unlock')),
                ('points', models.IntegerField(default=0, help_text='Points awarded when unlocked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'tier', 'requirement_value'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
