# Generated by Django 5.0.1 on 2025-11-13 18:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscles_targeted', models.JSONField(help_text='List of muscle groups targeted')),
                ('duration', models.IntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('intensity', models.CharField(choices=[('light', 'Light'), ('moderate', 'Moderate'), ('intense', 'Intense')], max_length=20)),
                ('goal', models.CharField(choices=[('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('endurance', 'Endurance')], max_length=20)),
                ('equipment', models.CharField(choices=[('bodyweight', 'Bodyweight'), ('home', 'Home Equipment'), ('gym', 'Full Gym')], max_length=20)),
                ('workout_plan', models.JSONField(help_text='Complete workout plan with exercises')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateField(auto_now_add=True)),
                ('muscles_targeted', models.JSONField(help_text='List of muscle groups targeted')),
                ('duration', models.IntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('intensity', models.CharField(choices=[('light', 'Light'), ('moderate', 'Moderate'), ('intense', 'Intense')], max_length=20)),
                ('goal', models.CharField(blank=True, choices=[('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('endurance', 'Endurance')], max_length=20, null=True)),
                ('equipment', models.CharField(choices=[('bodyweight', 'Bodyweight'), ('home', 'Home Equipment'), ('gym', 'Full Gym')], max_length=20)),
                ('exercises_completed', models.JSONField(help_text='List of exercises with sets, reps, etc.')),
                ('points_earned', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Workout histories',
                'ordering': ['-workout_date', '-created_at'],
            },
        ),
    ]
