# Generated by Django 5.0.1 on 2026-01-07 23:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workouthistory_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('weeks', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('days_per_week', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('goal', models.CharField(choices=[('strength', 'Build Strength'), ('hypertrophy', 'Build Muscle'), ('endurance', 'Build Endurance'), ('weight_loss', 'Lose Weight'), ('general_fitness', 'General Fitness')], max_length=20)),
                ('icon', models.CharField(default='💪', max_length=50)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('estimated_duration_per_session', models.IntegerField(default=45, help_text='Average duration per session in minutes')),
                ('equipment_needed', models.CharField(choices=[('bodyweight', 'Bodyweight'), ('home', 'Home Equipment'), ('gym', 'Full Gym')], default='gym', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'difficulty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProgramEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('current_week', models.IntegerField(default=1)),
                ('current_day', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_workout_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_enrollments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='workouts.workoutprogram')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('day_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(help_text="e.g., 'Push Day', 'Leg Day'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('muscles_targeted', models.JSONField(help_text='List of muscle groups targeted')),
                ('duration', models.IntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('intensity', models.CharField(choices=[('light', 'Light'), ('moderate', 'Moderate'), ('intense', 'Intense')], max_length=20)),
                ('exercise_template', models.JSONField(blank=True, help_text='Pre-defined exercises for this day, or null to generate', null=True)),
                ('is_rest_day', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_days', to='workouts.workoutprogram')),
            ],
            options={
                'ordering': ['week_number', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDayCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('program_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='workouts.programday')),
                ('workout_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_completions', to='workouts.workouthistory')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_days', to='workouts.userprogramenrollment')),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('enrollment', 'program_day')},
            },
        ),
        migrations.AddConstraint(
            model_name='userprogramenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'program'), name='unique_active_enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='programday',
            unique_together={('program', 'week_number', 'day_number')},
        ),
    ]
