# Generated by Django 5.0.1 on 2025-11-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('primary_muscle', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('quads', 'Quadriceps'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('abs', 'Abs'), ('obliques', 'Obliques')], max_length=20)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('equipment', models.CharField(choices=[('bodyweight', 'Bodyweight'), ('dumbbells', 'Dumbbells'), ('barbell', 'Barbell'), ('machine', 'Machine'), ('cable', 'Cable'), ('resistance_band', 'Resistance Band'), ('kettlebell', 'Kettlebell')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('sets_min', models.IntegerField(default=3)),
                ('sets_max', models.IntegerField(default=4)),
                ('reps_min', models.IntegerField(default=8)),
                ('reps_max', models.IntegerField(default=12)),
                ('rest_seconds', models.IntegerField(default=60)),
                ('description', models.TextField()),
                ('instructions', models.JSONField(help_text='Step-by-step instructions')),
                ('tips', models.JSONField(blank=True, default=list, help_text='Exercise tips')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['primary_muscle', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('muscle_groups', models.JSONField(help_text='List of muscle groups targeted')),
                ('recommended_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
