# Generated by Django 5.0.1 on 2025-12-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='gif_url',
            field=models.URLField(blank=True, help_text='URL to animated GIF demonstration', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to exercise demonstration image', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to video demonstration (YouTube, etc.)', null=True),
        ),
    ]
